### ISSUE TITLE
Assignment 4

### ISSUE THREAD

**Issue by hieutrluu** [BichNgoc174/MachineLearningProblemSets#3]
Bạn ơi, có câu hỏi gì thì hỏi mình nhé chứ bài bạn làm không được tốt so với lớp

Nhận xét: 
- chưa thực hiện data cleaning
- data visualisation sơ sài
- không có kết luận extract insight từ data

**Comment by BichNgoc174** [comment]
> Bạn ơi, có câu hỏi gì thì hỏi mình nhé chứ bài bạn làm không được tốt so với lớp
> 
> Nhận xét:
> 
> * chưa thực hiện data cleaning
> * data visualisation sơ sài
> * không có kết luận extract insight từ data
